/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.dialogs;

import entities.Repuesto;
import entities.Stock;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import services.RepuestoServ;
import util.VerificadorCampos;

/**
 *
 * @author Usuario
 */
public class JDialogEditarRepuesto extends javax.swing.JDialog {

    private final VerificadorCampos verificadorCampos = new VerificadorCampos();

    private final RepuestoServ repuestoServ = new RepuestoServ();

    private String codBarraCargaPantalla;

    private Repuesto repuestoCargaPantalla;

    /**
     * Creates new form JDialogEditarRepuesto
     *
     * @param parent
     * @param modal
     */
    public JDialogEditarRepuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public void setCodBarra(String codBarra) {
        this.codBarraCargaPantalla = codBarra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCodBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDetalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCantidadStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfUbicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfLote = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfObservaciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICANDO UN REPUESTO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código de Barras");

        jLabel2.setText("Marca");

        jLabel3.setText("Detalle");

        jLabel4.setText("Precio");

        jLabel5.setText("Cantidad de Stock");

        jLabel6.setText("Ubicación");

        jLabel7.setText("Lote");

        jLabel8.setText("Observaciones");

        jLabel9.setText("*Los campos \"lote\" y \"observaciones\" pueden quedar vacíos.");

        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonGuardar.setText("GUARDAR CAMBIOS");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(354, 354, 354))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtfMarca)
                            .addComponent(jtfCodBarra)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPrecio)
                            .addComponent(jtfDetalle)
                            .addComponent(jtfCantidadStock)
                            .addComponent(jtfUbicacion)
                            .addComponent(jtfLote)
                            .addComponent(jtfObservaciones))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jButtonGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //CONTROL DE VACÍOS
        try {
            verificadorCampos.verificarVacio(jtfCodBarra.getText().trim(),jLabel1.getText());
            verificadorCampos.verificarVacio(jtfMarca.getText().trim(),jLabel2.getText());
            verificadorCampos.verificarVacio(jtfDetalle.getText().trim(),jLabel3.getText());
            verificadorCampos.verificarVacio(jtfPrecio.getText().trim(),jLabel4.getText());
            verificadorCampos.verificarVacio(jtfCantidadStock.getText().trim(),jLabel5.getText());
            verificadorCampos.verificarVacio(jtfUbicacion.getText().trim(),jLabel6.getText());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "HAY CAMPOS OBLIGATORIOS VACÍOS",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        //CONTROL DE LARGOS
        try {
            verificadorCampos.verificaLargo(jtfCodBarra.getText().trim(), 25, jLabel1.getText());
            verificadorCampos.verificaLargo(jtfMarca.getText().trim(), 100, jLabel2.getText());
            verificadorCampos.verificaLargo(jtfDetalle.getText().trim(), 100, jLabel3.getText());
            verificadorCampos.verificaLargo(jtfPrecio.getText().trim(), 15, jLabel4.getText());
            verificadorCampos.verificaLargo(jtfCantidadStock.getText().trim(), 11, jLabel5.getText());
            verificadorCampos.verificaLargo(jtfUbicacion.getText().trim(), 100, jLabel6.getText());
            verificadorCampos.verificaLargo(jtfLote.getText().trim(), 100, jLabel7.getText());
            verificadorCampos.verificaLargo(jtfObservaciones.getText().trim(), 200, jLabel8.getText());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                     "CAMPOS MUY LARGOS", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //CONTROL DE FORMATOS
        try {
            verificadorCampos.verificaFormatoDouble(jtfPrecio.getText().trim(), jLabel4.getText());
            verificadorCampos.verificaFormatoInteger(jtfCantidadStock.getText().trim(), jLabel5.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "HAY CAMPOS NUMÉRICOS EN MAL FORMATO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codBarra = jtfCodBarra.getText().trim();
        String marca = jtfMarca.getText().trim();
        String detalle = jtfDetalle.getText().trim();
        Double precio = Double.valueOf(jtfPrecio.getText().trim());
        Integer cantidad = Integer.valueOf(jtfCantidadStock.getText().trim());
        String ubicacion = jtfUbicacion.getText().trim();
        String lote = jtfLote.getText().trim();
        String observaciones = jtfObservaciones.getText().trim();

        Stock stock = new Stock(repuestoCargaPantalla.getStock().getId(), cantidad, ubicacion, lote, observaciones);
        Repuesto repuesto = new Repuesto(repuestoCargaPantalla.getId(), codBarra, marca, detalle, precio, stock);

        //INICIO CONFIRMACIÓN
        int opcionElegida = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea editar este repuesto?",
                "CONFIRMACIÓN DE EDICIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcionElegida == JOptionPane.YES_OPTION) {
            try {
                //SI EL COD BARRA CAMBIÓ HAY Q VERIFICAR QUE NO EXISTA YA UNO CON ESE COD
                if (!codBarraCargaPantalla.equals(codBarra)) {
                    //SI YA EXISTE...
                    if (repuestoServ.existeCodBarra(repuesto)) {
                        JOptionPane.showMessageDialog(null, "Ya existe un producto con ese código de barras",
                                "ERROR DE GUARDADO", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                repuestoServ.modificarRepuesto(repuesto);
                this.dispose();
            } catch (NullPointerException | HibernateException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR DE GUARDADO",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /*
    CARGA LAS CAJAS DE TEXTO CON LOS DATOS DEL REPUESTO A MODIFICAR
    */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        repuestoCargaPantalla = repuestoServ.buscarPorCodBarraExacto(codBarraCargaPantalla);

        jtfCodBarra.setText(repuestoCargaPantalla.getCodBarra());
        jtfMarca.setText(repuestoCargaPantalla.getMarca());
        jtfDetalle.setText(repuestoCargaPantalla.getDetalle());
        jtfPrecio.setText(repuestoCargaPantalla.getPrecio().toString());
        jtfCantidadStock.setText(repuestoCargaPantalla.getStock().getCantidad().toString());
        jtfUbicacion.setText(repuestoCargaPantalla.getStock().getUbicacion());
        jtfLote.setText(repuestoCargaPantalla.getStock().getLote());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEditarRepuesto dialog = new JDialogEditarRepuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfCantidadStock;
    private javax.swing.JTextField jtfCodBarra;
    private javax.swing.JTextField jtfDetalle;
    private javax.swing.JTextField jtfLote;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfObservaciones;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfUbicacion;
    // End of variables declaration//GEN-END:variables
}
