package GUI.dialogs;

import entities.DetalleRetiro;
import entities.NotaRetiro;
import entities.Repuesto;
import entities.VentaRepuesto;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.RepuestoServ;

/**
 *
 * @author Usuario
 */
public class JDialogNuevaVenta extends javax.swing.JDialog {

    //constantes para tabla
    private final String COL_COD_BARRA = "COD BARRA";
    private final String COL_DETALLE = "DETALLE";
    private final String COL_MARCA = "MARCA";
    private final String COL_PRECIO = "PRECIO UNI";
    private final String COL_CANTIDAD = "CANTIDAD";
    private final String COL_PRECIO_TOTAL = "PRECIO TOTAL";

    private final DefaultTableModel tabla = new DefaultTableModel(new Object[]{
        COL_COD_BARRA, COL_DETALLE, COL_MARCA, COL_PRECIO, COL_CANTIDAD, COL_PRECIO_TOTAL}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // ninguna celda editable
        }
    };

    private final RepuestoServ repuestoServ = new RepuestoServ();

    //TO-DO: QUITAR LISTA PRECINDIBLE
    private List<Long> idsRepuestosAgregados = new ArrayList<>();

    private NotaRetiro nota = new NotaRetiro();

    private VentaRepuesto ventaParaTotalJlabel = new VentaRepuesto();

    private List<DetalleRetiro> detalles = new ArrayList<>();

    public JDialogNuevaVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ////MÉTODOS CUANDO SE INICIA LA VENTANA
        setTabla();
        this.nota.setId(null);
        this.nota.setDetallesRetiro(this.detalles);
        jLabFecha.setText("FECHA: " + LocalDate.now());

        this.ventaParaTotalJlabel.setNotaRetiro(nota);
    }

    private void setTabla() {
        jTableRepuestos = new JTable(tabla);
        jScrollPane1.setViewportView(jTableRepuestos);
    }

    private void agregaRepuestoTabla(Repuesto repuesto, Integer cantidad) {
        BigDecimal total = repuesto.getPrecio().multiply(BigDecimal.valueOf(cantidad));
        tabla.addRow(new Object[]{
            repuesto.getCodBarra(),
            repuesto.getDetalle(),
            repuesto.getMarca(),
            "$ " + repuesto.getPrecio(),
            cantidad,
            "$ " + total
        });
    }

    public void recibeRepuesto(Repuesto repuesto, Integer cantidad) {
        //TO-DO:HACER BIEN LA ACTUALIZACION DE STOCK AL VENDER
        int nuevaCantidadStock = repuesto.getStock().getCantidad() - cantidad;
        repuesto.getStock().setCantidad(nuevaCantidadStock);

        this.idsRepuestosAgregados.add(repuesto.getId());
        agregaRepuestoTabla(repuesto, cantidad);
        DetalleRetiro d = new DetalleRetiro(null, cantidad, repuesto);
        //TO-DO:HACER EL MÉTODO PARA ESTO EN LA CLASE NOTA
        this.detalles.add(d);
        jButPagar.setEnabled(false);
        BigDecimal bd = this.ventaParaTotalJlabel.calculaMontoTotal();
        jLabTotal.setText("TOTAL: $ " + String.valueOf(bd));
    }

    public List<Long> getAgregados() {
        return this.idsRepuestosAgregados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRepuestos = new javax.swing.JTable();
        jLabTotal = new javax.swing.JLabel();
        jButPagar = new javax.swing.JButton();
        jButEmitirNota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButAgregarRepuesto = new javax.swing.JButton();
        jButQuitarRepuesto = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButCancelarVenta = new javax.swing.JButton();
        jButLimpiarTabla = new javax.swing.JButton();
        jButModificarCantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("cargar nueva venta");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabFecha.setForeground(new java.awt.Color(0, 0, 0));
        jLabFecha.setText("FECHA:");

        jTableRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRepuestos.setShowGrid(true);
        jScrollPane1.setViewportView(jTableRepuestos);

        jLabTotal.setForeground(new java.awt.Color(0, 0, 0));
        jLabTotal.setText("TOTAL:");

        jButPagar.setText("PAGAR");
        jButPagar.setEnabled(false);
        jButPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPagarActionPerformed(evt);
            }
        });

        jButEmitirNota.setText("EMITIR NOTA DE RETIRO");
        jButEmitirNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEmitirNotaActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Debe emitir una nota de retiro para poder continuar con el pago");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButEmitirNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabFecha)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabTotal)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButPagar)
                    .addComponent(jButEmitirNota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jButAgregarRepuesto.setText("AGREGAR REPUESTO");
        jButAgregarRepuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButAgregarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAgregarRepuestoActionPerformed(evt);
            }
        });

        jButQuitarRepuesto.setText("QUITAR REPUESTO");
        jButQuitarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButQuitarRepuestoActionPerformed(evt);
            }
        });

        jButton5.setText("APLICAR DESCUENTO");

        jButCancelarVenta.setText("CANCELAR VENTA");
        jButCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarVentaActionPerformed(evt);
            }
        });

        jButLimpiarTabla.setText("LIMPIAR TABLA");
        jButLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLimpiarTablaActionPerformed(evt);
            }
        });

        jButModificarCantidad.setText("CAMBIAR CANTIDAD");
        jButModificarCantidad.setMargin(new java.awt.Insets(2, 10, 3, 10));
        jButModificarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButModificarCantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButLimpiarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButCancelarVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButModificarCantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButQuitarRepuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButAgregarRepuesto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButAgregarRepuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButQuitarRepuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButModificarCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButLimpiarTabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButCancelarVenta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButAgregarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAgregarRepuestoActionPerformed
        jDialogAgregarRepuestoVenta jdiaAgregarRepuestoVenta = new jDialogAgregarRepuestoVenta(null, true, this);
        jdiaAgregarRepuestoVenta.setVisible(true);
    }//GEN-LAST:event_jButAgregarRepuestoActionPerformed

    private void jButCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarVentaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButCancelarVentaActionPerformed

    private void jButLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLimpiarTablaActionPerformed
        this.detalles.clear();
        this.idsRepuestosAgregados.clear();
        tabla.setRowCount(0);
        jButPagar.setEnabled(false);
        jLabTotal.setText("TOTAL: $ ");
    }//GEN-LAST:event_jButLimpiarTablaActionPerformed

    private void jButQuitarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButQuitarRepuestoActionPerformed
        int filaParaModificar = jTableRepuestos.getSelectedRow();
        if (filaParaModificar == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado un repuesto de la tabla.",
                    "DEBE SELECCIONAR UN REPUESTO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codBarraSeleccionTabla = jTableRepuestos.getValueAt(filaParaModificar, 0).toString();
        tabla.removeRow(filaParaModificar);
        //TO-DO: MEJORAR FORMA DE QUITAR ID DE LA LISTA
        Repuesto repuesto = repuestoServ.buscarPorCodBarraExacto(codBarraSeleccionTabla);
        this.idsRepuestosAgregados.remove(repuesto.getId());
//        for (){
//            
//        }
//        DetalleRetiro d = nota.getDetallesRetiro().get();
//        detalles.remove(repuesto);
        jButPagar.setEnabled(false);
    }//GEN-LAST:event_jButQuitarRepuestoActionPerformed

    private void jButPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPagarActionPerformed
        JDialogPago jDialogPago = new JDialogPago(null, true, nota);
        jDialogPago.setVisible(true);
    }//GEN-LAST:event_jButPagarActionPerformed

    private void jButEmitirNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEmitirNotaActionPerformed
        if (this.detalles.isEmpty() || this.detalles == null) {
            JOptionPane.showMessageDialog(null, "No hay repuestos agregados para la venta.",
                    "DEBE AGREGAR REPUESTOS",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            nota.setFecha(LocalDate.now());
            jButPagar.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Se ha emitido la nota de retiro correctamente.",
                    "EMISIÓN DE NOTA",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButEmitirNotaActionPerformed

    private void jButModificarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButModificarCantidadActionPerformed

    }//GEN-LAST:event_jButModificarCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogNuevaVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogNuevaVenta dialog = new JDialogNuevaVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAgregarRepuesto;
    private javax.swing.JButton jButCancelarVenta;
    private javax.swing.JButton jButEmitirNota;
    private javax.swing.JButton jButLimpiarTabla;
    private javax.swing.JButton jButModificarCantidad;
    private javax.swing.JButton jButPagar;
    private javax.swing.JButton jButQuitarRepuesto;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabFecha;
    private javax.swing.JLabel jLabTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRepuestos;
    // End of variables declaration//GEN-END:variables
}
