/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.dialogs;

import entities.Repuesto;
import entities.Stock;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import services.RepuestoServ;
import util.VerificadorCampos;

/**
 *
 * @author Usuario
 */
public class JDialogAgregarRepuesto extends javax.swing.JDialog {

    private final RepuestoServ repuestoServ = new RepuestoServ();

    private final VerificadorCampos verificadorCampos = new VerificadorCampos();

    /**
     * Creates new form JDialogAgregarRepuesto
     */
    public JDialogAgregarRepuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCodBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDetalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCantidadStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfStockMinimo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfUbicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfLote = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfObservaciones = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Repuesto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(487, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Código de barras");

        jtfCodBarra.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Marca");

        jtfMarca.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Detalle");

        jtfDetalle.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtfDetalle.setToolTipText("Información detallada del nombre del producto");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Precio");

        jtfPrecio.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de Stock");

        jtfCantidadStock.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jtfCantidadStock.setText(" ");

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad de Stock Mínimo");

        jtfStockMinimo.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Ubicación");

        jtfUbicacion.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Lote");

        jtfLote.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Observaciones");

        jtfObservaciones.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jButtonAgregar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButtonAgregar.setText("AGREGAR");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel9.setText("*Los campos \"lote\" y \"observaciones\" no son obligatorios.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfObservaciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLote, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUbicacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodBarra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDetalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfStockMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jtfCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jtfDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(jtfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jtfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        //CONTROL DE VACÍOS
        try {
            verificadorCampos.verificarVacio(jtfCodBarra.getText().trim(),jLabel1.getText());
            verificadorCampos.verificarVacio(jtfMarca.getText().trim(),jLabel2.getText());
            verificadorCampos.verificarVacio(jtfDetalle.getText().trim(),jLabel3.getText());
            verificadorCampos.verificarVacio(jtfPrecio.getText().trim(),jLabel4.getText());
            verificadorCampos.verificarVacio(jtfCantidadStock.getText().trim(),jLabel5.getText());
            verificadorCampos.verificarVacio(jtfStockMinimo.getText().trim(), jLabel10.getText());
            verificadorCampos.verificarVacio(jtfUbicacion.getText().trim(),jLabel6.getText());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "HAY CAMPOS OBLIGATORIOS VACÍOS",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //CONTROL DE LARGOS
        try {
            verificadorCampos.verificaLargo(jtfCodBarra.getText().trim(), 25, jLabel1.getText());
            verificadorCampos.verificaLargo(jtfMarca.getText().trim(), 100, jLabel2.getText());
            verificadorCampos.verificaLargo(jtfDetalle.getText().trim(), 100, jLabel3.getText());
            verificadorCampos.verificaLargo(jtfPrecio.getText().trim(), 15, jLabel4.getText());
            verificadorCampos.verificaLargo(jtfCantidadStock.getText().trim(), 11, jLabel5.getText());
            verificadorCampos.verificaLargo(jtfStockMinimo.getText().trim(), 11, jLabel10.getText());
            verificadorCampos.verificaLargo(jtfUbicacion.getText().trim(), 100, jLabel6.getText());
            verificadorCampos.verificaLargo(jtfLote.getText().trim(), 100, jLabel7.getText());
            verificadorCampos.verificaLargo(jtfObservaciones.getText().trim(), 200, jLabel8.getText());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(),
                     "CAMPOS MUY LARGOS", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //CONTROL DE FORMATOS
        try {
            verificadorCampos.verificaFormatoDouble(jtfPrecio.getText().trim(), jLabel4.getText());
            verificadorCampos.verificaFormatoInteger(jtfCantidadStock.getText().trim(), jLabel5.getText());
            verificadorCampos.verificaFormatoInteger(jtfStockMinimo.getText().trim(), jLabel10.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "HAY CAMPOS NUMÉRICOS EN MAL FORMATO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codBarra = jtfCodBarra.getText().trim();
        String marca = jtfMarca.getText().trim();
        String detalle = jtfDetalle.getText().trim();
        BigDecimal precio = BigDecimal.valueOf(Double.parseDouble(jtfPrecio.getText().trim())).setScale(2,RoundingMode.HALF_UP);
        Integer cantidad = Integer.valueOf(jtfCantidadStock.getText().trim());
        Integer cantMinima = Integer.valueOf(jtfStockMinimo.getText().trim());
        String ubicacion = jtfUbicacion.getText().trim();
        String lote = jtfLote.getText().trim();
        String observaciones = jtfObservaciones.getText().trim();

        Stock stock = new Stock(null, cantidad, cantMinima,ubicacion, lote, observaciones);
        Repuesto repuesto = new Repuesto(null, codBarra, marca, detalle, precio, stock);

        //INICIO CONFIRMACIÓN
        int opcionElegida = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea crear este repuesto?",
                "CONFIRMACIÓN DE CREACIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcionElegida == JOptionPane.YES_OPTION) {
            try {
                repuestoServ.cargarRepuesto(repuesto);
                this.dispose();
            } catch (NullPointerException | HibernateException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR DE STOCK",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAgregarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAgregarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAgregarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAgregarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAgregarRepuesto dialog = new JDialogAgregarRepuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jtfCantidadStock;
    private javax.swing.JTextField jtfCodBarra;
    private javax.swing.JTextField jtfDetalle;
    private javax.swing.JTextField jtfLote;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfObservaciones;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfStockMinimo;
    private javax.swing.JTextField jtfUbicacion;
    // End of variables declaration//GEN-END:variables
}
