package GUI.dialogs;

import GUI.panels.PanelDeposito;
import entities.Repuesto;
import entities.Stock;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import services.RepuestoServ;
import util.ConversorUnidades;
import util.VerificadorCampos;

/**
 *
 * @author Usuario
 */
public class JDialogEditarRepuesto extends javax.swing.JDialog {

    private final RepuestoServ repuestoServ = new RepuestoServ();

    private PanelDeposito pdepo;

    private Repuesto repuesto;

    /**
     * Creates new form JDialogEditarRepuesto
     */
    public JDialogEditarRepuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public JDialogEditarRepuesto(java.awt.Frame parent, boolean modal, PanelDeposito pdepo, Repuesto repuesto) {
        super(parent, modal);
        initComponents();

        this.pdepo = pdepo;
        this.repuesto = repuesto;
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCodBarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDetalle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfCantidadStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfStockMinimo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfUbicacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfLote = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfObservaciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jcbMarcas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jcbUbicaciones = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jcbUnidadMedida = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFICANDO UN REPUESTO");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Código de Barras");

        jtfCodBarra.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Marca");

        jtfMarca.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Detalle");

        jtfDetalle.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Precio");

        jtfPrecio.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad de Stock");

        jtfCantidadStock.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad de Stock Mínimo");

        jtfStockMinimo.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Ubicación");

        jtfUbicacion.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Lote");

        jtfLote.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Observaciones");

        jtfObservaciones.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        jLabel9.setText("*Los campos \"lote\" y \"observaciones\" no son obligatorios.");

        jButtonGuardar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButtonGuardar.setText("GUARDAR CAMBIOS");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Marca ya existente");

        jcbMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nueva marca...", "Corven", "Fate", "Mirgor", "Bosch", "Valeo", "Monroe", "SKF", "Mopar", "Moura", "Magneti Marelli", "Omnicraft" }));
        jcbMarcas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMarcasItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Ubicación ya existente");

        jcbUbicaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nueva ubicación...", "Depósito a", "Depósito b", "Depósito c", "Depósito d", "Depósito e" }));
        jcbUbicaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbUbicacionesItemStateChanged(evt);
            }
        });

        jLabel13.setText("Unidad medida");

        jcbUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad", "Metros", "Litros", "Kilos", "Otra..." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfDetalle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodBarra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLote, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfObservaciones, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUbicacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jcbUnidadMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfStockMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(jcbUbicaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel12))
                                    .addComponent(jcbMarcas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(jtfDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantidadStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(jtfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jtfObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //toma de inputs
        String codBarra = jtfCodBarra.getText().trim();
        String marca;
        if (jtfMarca.isEnabled()) {
            marca = jtfMarca.getText().trim();
        } else {
            marca = (String) jcbMarcas.getSelectedItem();
        }
        String detalle = jtfDetalle.getText().trim();
        String inputPrecio = jtfPrecio.getText().trim();
        String inputCantidadStock = jtfCantidadStock.getText().trim();
        String inputCantStockMinima = jtfStockMinimo.getText().trim();
        String unidadMedida = (String) jcbUnidadMedida.getSelectedItem();
        String ubicacion;
        if (jtfUbicacion.isEnabled()) {
            ubicacion = jtfUbicacion.getText().trim();
        } else {
            ubicacion = (String) jcbUbicaciones.getSelectedItem();
        }
        String lote = jtfLote.getText().trim();
        String observaciones = jtfObservaciones.getText().trim();

        BigDecimal precio;
        Double cantidadStock;
        Double cantStockMinima;

        //verifiaciones y conversión
        try {
            VerificadorCampos.inputTextoGenerico(codBarra, null, 25, true, true, null);
            if (jtfMarca.isEnabled()) {
                VerificadorCampos.inputTextoGenerico(marca, null, 30, true, true, null);
            }
            VerificadorCampos.inputTextoGenerico(detalle, null, 40, true, true, null);
            VerificadorCampos.dinero(inputPrecio, true);
            precio = ConversorUnidades.bdParaDinero(inputPrecio);
            VerificadorCampos.cantidadStock(inputCantidadStock, true);
            cantidadStock = ConversorUnidades.double2Decimales(inputCantidadStock);
            VerificadorCampos.cantidadStock(inputCantStockMinima, true);
            cantStockMinima = ConversorUnidades.double2Decimales(inputCantStockMinima);
            if (jtfUbicacion.isEnabled()) {
                VerificadorCampos.inputTextoGenerico(ubicacion, null, 30, true, true, null);
            }
            VerificadorCampos.inputTextoGenerico(lote, null, 40, false, true, null);
            VerificadorCampos.inputTextoGenerico(observaciones, null, 100, false, true, null);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, nfe.getMessage(), "ATENCIÓN",
                    JOptionPane.WARNING_MESSAGE);
            return;
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(null, iae.getMessage(), "ATENCIÓN",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Stock stock = new Stock(this.repuesto.getStock().getId(), cantidadStock, cantStockMinima, unidadMedida, ubicacion, lote, observaciones, true);
        Repuesto repuestoMerge = new Repuesto(this.repuesto.getId(), codBarra, marca, detalle, precio, true, stock);

        //INICIO CONFIRMACIÓN
        int opcionElegida = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea editar este repuesto?",
                "CONFIRMACIÓN DE EDICIÓN", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcionElegida == JOptionPane.YES_OPTION) {
            try {
                repuestoServ.modificarRepuesto(repuestoMerge, this.repuesto.getCodBarra());
                JOptionPane.showMessageDialog(null, "Repuesto modificado correctamente.",
                        "MODIFICACIÓN DE REPUESTO", JOptionPane.INFORMATION_MESSAGE);
                this.pdepo.actualizaTabla();
                this.dispose();
            } catch (NullPointerException | HibernateException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR DE GUARDADO",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /*
    CARGA LAS CAJAS DE TEXTO CON LOS DATOS DEL REPUESTO A MODIFICAR
     */
    private void cargarDatos() {
        jtfCodBarra.setText(this.repuesto.getCodBarra());
        //TO-DO:OPTIMIZAR ESTO Y QUE TOME LAS MARCAS Y DEPO DE BASE DE DATOS
        //carga a jcb trucha para parcial
        jcbMarcas.setSelectedItem(this.repuesto.getMarca());
        if (jcbMarcas.getSelectedIndex() == 0) {
            jtfMarca.setEnabled(true);
            jtfMarca.setText(this.repuesto.getMarca());
        } else {
            jtfMarca.setEnabled(false);
        }
        jtfDetalle.setText(this.repuesto.getDetalle());
        jtfPrecio.setText(this.repuesto.getPrecio().toString());
        jcbUnidadMedida.setSelectedItem(this.repuesto.getStock().getUnidadMedida());
        jtfCantidadStock.setText(this.repuesto.getStock().getCantidad().toString());
        jtfStockMinimo.setText(this.repuesto.getStock().getCantMinima().toString());
        //TO-DO:OPTIMIZAR ESTO Y QUE TOME LAS MARCAS Y UBI DE BASE DE DATOS
        //carga a jcb trucha para parcial
        jcbUbicaciones.setSelectedItem(this.repuesto.getStock().getUbicacion());
        if (jcbUbicaciones.getSelectedIndex() == 0) {
            jcbUbicaciones.setEnabled(true);
            jtfUbicacion.setText(this.repuesto.getStock().getUbicacion());
        } else {
            jtfUbicacion.setEnabled(false);
        }
        jtfLote.setText(this.repuesto.getStock().getLote());
        jtfObservaciones.setText(this.repuesto.getStock().getObservaciones());
    }

    private void jcbMarcasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMarcasItemStateChanged
        if (jcbMarcas.getSelectedIndex() != 0) {
            jtfMarca.setText("");
            jtfMarca.setEnabled(false);
        } else {
            jtfMarca.setEnabled(true);
        }
    }//GEN-LAST:event_jcbMarcasItemStateChanged

    private void jcbUbicacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbUbicacionesItemStateChanged
        if (jcbUbicaciones.getSelectedIndex() != 0) {
            jtfUbicacion.setText("");
            jtfUbicacion.setEnabled(false);
        } else {
            jtfUbicacion.setEnabled(true);
        }
    }//GEN-LAST:event_jcbUbicacionesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEditarRepuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEditarRepuesto dialog = new JDialogEditarRepuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcbMarcas;
    private javax.swing.JComboBox<String> jcbUbicaciones;
    private javax.swing.JComboBox<String> jcbUnidadMedida;
    private javax.swing.JTextField jtfCantidadStock;
    private javax.swing.JTextField jtfCodBarra;
    private javax.swing.JTextField jtfDetalle;
    private javax.swing.JTextField jtfLote;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfObservaciones;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfStockMinimo;
    private javax.swing.JTextField jtfUbicacion;
    // End of variables declaration//GEN-END:variables
}
