package GUI;

import entities.Usuario;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Usuario
 */
public class JFrameHome extends javax.swing.JFrame {

    public Usuario usuarioLogueado;
    
    private JFrameHome() {
        initComponents();
        this.setResizable(false);
        
    }
    
    public JFrameHome(Usuario usuarioLogueado) {
        initComponents();
        this.setResizable(false);
        
        this.usuarioLogueado=usuarioLogueado;
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imgs/icono.png"));
        setIconImage(image);
    }
    
    public Usuario tomarUsuarioLogueado(){
        return this.usuarioLogueado;
    }
    
    public void mostrarPanel(String nombrePanel){
        CardLayout cl = (CardLayout) jPanelCardLayout.getLayout();
        cl.show(jPanelCardLayout, nombrePanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCardLayout = new javax.swing.JPanel();
        panelOpciones1 = new GUI.panels.PanelOpciones();
        panelOpciones1 = new GUI.panels.PanelOpciones(this);
        panelDeposito1 = new GUI.panels.PanelDeposito();
        panelDeposito1 = new GUI.panels.PanelDeposito(this);
        panelNuevaVenta1 = new GUI.panels.PanelNuevaVenta();
        panelNuevaVenta1 = new GUI.panels.PanelNuevaVenta(this);
        panelVentas1 = new GUI.panels.PanelVentas();
        panelVentas1 = new GUI.panels.PanelVentas(this);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jPanelCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardLayout.setLayout(new java.awt.CardLayout());
        jPanelCardLayout.add(panelOpciones1, "panelOpciones");
        jPanelCardLayout.add(panelDeposito1, "panelDeposito");
        jPanelCardLayout.add(panelNuevaVenta1, "panelNuevaVenta");
        jPanelCardLayout.add(panelVentas1, "panelVentas");

        jMenu1.setText("Ventana");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCardLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCardLayout;
    private GUI.panels.PanelDeposito panelDeposito1;
    private GUI.panels.PanelNuevaVenta panelNuevaVenta1;
    private GUI.panels.PanelOpciones panelOpciones1;
    private GUI.panels.PanelVentas panelVentas1;
    // End of variables declaration//GEN-END:variables
}
