package GUI;

import GUI.dialogs.JDialogAgregarRepuesto;
import GUI.dialogs.JDialogEditarRepuesto;
import entities.Repuesto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.RepuestoServ;
import util.VerificadorCampos;

public class JFrameDeposito extends javax.swing.JFrame {

    private final RepuestoServ repuestoServ = new RepuestoServ();

    private final String COL_COD_BARRA = "COD BARRA";
    private final String COL_DETALLE = "DETALLE";
    private final String COL_MARCA = "MARCA";
    private final String COL_PRECIO = "PRECIO";
    private final String COL_CANTI_STOCK = "CANTIDAD STOCK";

    private final Integer CB_COD_BARRA = 0;
    private final Integer CB_DETALLE = 1;

    private final VerificadorCampos verificadorCampos = new VerificadorCampos();

    private final DefaultTableModel tabla = new DefaultTableModel(new Object[]{
        COL_COD_BARRA, COL_DETALLE, COL_MARCA, COL_PRECIO, COL_CANTI_STOCK}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // ninguna celda editable
        }
    };

    private List<Repuesto> listaParaTabla;

    /**
     * Creates new form JFrameDeposito
     */
    public JFrameDeposito() {
        initComponents();

        ////MÉTODOS CUANDO SE INICIA LA VENTANA
        setTabla();
        listaParaTabla = repuestoServ.todosRepuestos();
        llenaTabla(listaParaTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButActualizar = new javax.swing.JButton();
        jButAgregarRepuesto = new javax.swing.JButton();
        jButModificar = new javax.swing.JButton();
        jButEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButNotaRetiro = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButBuscarRepuesto = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRepuestos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depósito");

        jButActualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButActualizar.setText("Actualizar Tabla");
        jButActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButActualizarActionPerformed(evt);
            }
        });

        jButAgregarRepuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButAgregarRepuesto.setText("Agregar Repuesto");
        jButAgregarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAgregarRepuestoActionPerformed(evt);
            }
        });

        jButModificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButModificar.setText("Modificar Repuesto");
        jButModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButModificarActionPerformed(evt);
            }
        });

        jButEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButEliminar.setText("Borrar Repuesto");
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("EN DESARROLLO");

        jButNotaRetiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButNotaRetiro.setText("Nueva Nota de Retiro");
        jButNotaRetiro.setEnabled(false);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButBuscarRepuesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButBuscarRepuesto.setText("Buscar Repuesto");
        jButBuscarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarRepuestoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar por:");

        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código de barras", "Detalle" }));

        jTableRepuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRepuestos);

        jMenu1.setText("Ventana");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButActualizar)
                    .addComponent(jButAgregarRepuesto)
                    .addComponent(jButModificar)
                    .addComponent(jButEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButNotaRetiro, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfBuscar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButBuscarRepuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(155, 155, 155)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButBuscarRepuesto)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButAgregarRepuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButNotaRetiro)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButAgregarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAgregarRepuestoActionPerformed
        JDialogAgregarRepuesto jdiaRep = new JDialogAgregarRepuesto(this, true);
        jdiaRep.setVisible(true);

    }//GEN-LAST:event_jButAgregarRepuestoActionPerformed

    private void jButBuscarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarRepuestoActionPerformed
        String input = jtfBuscar.getText().trim();
        try {
            verificadorCampos.verificarVacio(input, "Búsqueda");
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "HAY CAMPOS OBLIGATORIOS VACÍOS",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jComboBoxBuscar.getSelectedIndex() == CB_COD_BARRA) {
            listaParaTabla = repuestoServ.buscarPorCodBarra(input);
            tabla.setRowCount(0);
            llenaTabla(listaParaTabla);
            return;
        }
        if (jComboBoxBuscar.getSelectedIndex() == CB_DETALLE) {
            listaParaTabla = repuestoServ.buscarPorDetalle(input);
            tabla.setRowCount(0);
            llenaTabla(listaParaTabla);
        }

    }//GEN-LAST:event_jButBuscarRepuestoActionPerformed

    private void jButActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButActualizarActionPerformed
        jtfBuscar.setText("");
        tabla.setRowCount(0);
        listaParaTabla = repuestoServ.todosRepuestos();
        llenaTabla(listaParaTabla);
    }//GEN-LAST:event_jButActualizarActionPerformed

    private void jButModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButModificarActionPerformed
        int filaParaModificar = jTableRepuestos.getSelectedRow();
        if (filaParaModificar == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado un repuesto.", "DEBE SELECCIONAR UN REPUESTO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codBarra = jTableRepuestos.getValueAt(filaParaModificar, 0).toString();
        JDialogEditarRepuesto jDialogEditarRepuesto = new JDialogEditarRepuesto(this, true);
        jDialogEditarRepuesto.setCodBarra(codBarra);
        jDialogEditarRepuesto.setVisible(true);
    }//GEN-LAST:event_jButModificarActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed

        int filaParaModificar = jTableRepuestos.getSelectedRow();
        if (filaParaModificar == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado un repuesto.", "DEBE SELECCIONAR UN REPUESTO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codBarra = jTableRepuestos.getValueAt(filaParaModificar, 0).toString();
        Repuesto repuestoBorrar = repuestoServ.buscarPorCodBarraExacto(codBarra);
        //CONFIRMACIÓN
        int respuesta = JOptionPane.showConfirmDialog(null,
                "Esta a punto de borrar un repuesto, esta acción es irreversible. ¿Continuar?",
                "CONFIRMACIÓN DE BORRADO", JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            int respuesta2 = JOptionPane.showConfirmDialog(null,
                    "Confirmar eliminación de " + repuestoBorrar.getDetalle(),
                    "CONFIRMACIÓN DE BORRADO", JOptionPane.WARNING_MESSAGE);
            if (respuesta2 == JOptionPane.YES_OPTION) {
                repuestoServ.borrarRepuesto(repuestoBorrar);
            }
        }

    }//GEN-LAST:event_jButEliminarActionPerformed

    private void setTabla() {
        jTableRepuestos = new JTable(tabla);
        jScrollPane1.setViewportView(jTableRepuestos);
    }

    private void llenaTabla(List<Repuesto> listaParaLlenar) {
        listaParaLlenar.forEach(repuesto -> {
            tabla.addRow(new Object[]{
                repuesto.getCodBarra(),
                repuesto.getDetalle(),
                repuesto.getMarca(),
                "$ " + repuesto.getPrecio(),
                repuesto.getStock().getCantidad()
            });
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButActualizar;
    private javax.swing.JButton jButAgregarRepuesto;
    private javax.swing.JButton jButBuscarRepuesto;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JButton jButModificar;
    private javax.swing.JButton jButNotaRetiro;
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableRepuestos;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
