/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panels;

import GUI.JFrameHome;
import GUI.dialogs.JDialogNuevaVenta;

/**
 *
 * @author Usuario
 */
public class PanelOpciones extends javax.swing.JPanel {

    private JFrameHome home;
    
    public PanelOpciones() {
        initComponents();
    }
    
    public PanelOpciones(JFrameHome home) {
        initComponents();
        
        this.home = home;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButNuevaVenta = new javax.swing.JButton();
        jButVerVentas = new javax.swing.JButton();
        jButRepuestos = new javax.swing.JButton();
        jButClientes = new javax.swing.JButton();

        jButNuevaVenta.setBackground(new java.awt.Color(255, 204, 204));
        jButNuevaVenta.setForeground(new java.awt.Color(0, 0, 0));
        jButNuevaVenta.setText("NUEVA VENTA");
        jButNuevaVenta.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNuevaVentaActionPerformed(evt);
            }
        });

        jButVerVentas.setBackground(new java.awt.Color(204, 204, 255));
        jButVerVentas.setForeground(new java.awt.Color(0, 0, 0));
        jButVerVentas.setText("VER VENTAS");
        jButVerVentas.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerVentasActionPerformed(evt);
            }
        });

        jButRepuestos.setBackground(new java.awt.Color(153, 255, 153));
        jButRepuestos.setForeground(new java.awt.Color(0, 0, 0));
        jButRepuestos.setText("REPUESTOS");
        jButRepuestos.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButRepuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRepuestosActionPerformed(evt);
            }
        });

        jButClientes.setText("CLIENTES");
        jButClientes.setEnabled(false);
        jButClientes.setMargin(new java.awt.Insets(2, 2, 2, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jButClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButRepuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(372, 372, 372))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNuevaVentaActionPerformed
        JDialogNuevaVenta jDialogNuevaVenta = new JDialogNuevaVenta(home, false);
        jDialogNuevaVenta.setVisible(true);
    }//GEN-LAST:event_jButNuevaVentaActionPerformed

    private void jButRepuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRepuestosActionPerformed
        home.mostrarPanel("panelDeposito");
    }//GEN-LAST:event_jButRepuestosActionPerformed

    private void jButVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerVentasActionPerformed
        home.mostrarPanel("panelVentas");
    }//GEN-LAST:event_jButVerVentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButClientes;
    private javax.swing.JButton jButNuevaVenta;
    private javax.swing.JButton jButRepuestos;
    private javax.swing.JButton jButVerVentas;
    // End of variables declaration//GEN-END:variables
}
