package GUI.panels;

import GUI.JFrameHome;
import GUI.dialogs.JDialogVentaDetalles;
import entities.VentaRepuesto;
import enums.EstadoVentaRepuesto;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import services.VentaRepuestoServ;
import util.GeneradorPDF;
import util.VerificadorCampos;

/**
 *
 * @author Usuario
 */
public class PanelVentas extends javax.swing.JPanel {

    private JFrameHome home;

    //constantes para tabla
    private final String COD_VENTA = "COD VENTA";
    private final String ESTADO = "ESTADO";
    private final String FECHA = "FECHA";
    private final String MONTO = "MONTO";

    private final DefaultTableModel tabla = new DefaultTableModel(new Object[]{
        COD_VENTA, ESTADO, FECHA, MONTO}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // ninguna celda editable
        }
    };

    private VerificadorCampos verificadorCampos = new VerificadorCampos();

    private VentaRepuestoServ ventaServ = new VentaRepuestoServ();

    private List<VentaRepuesto> listaParaTabla = new ArrayList<>();

    public PanelVentas() {
        initComponents();
    }

    public PanelVentas(JFrameHome home) {
        initComponents();

        this.home = home;
        setTabla();
//        listaParaTabla = ventaServ.todasVentas();
        llenaTabla(listaParaTabla);
    }

    private void setTabla() {
        jTableVentas = new JTable(tabla);
        jScrollPane1.setViewportView(jTableVentas);
    }

    private void llenaTabla(List<VentaRepuesto> listaParaLlenar) {
        listaParaLlenar.forEach(venta -> {
            tabla.addRow(new Object[]{
                venta.getId(),
                venta.getEstadoVenta(),
                venta.getFechaVenta(),
                "$ " + venta.getMontoTotal()
            });
        });
    }

    private String tomaOrdenEligido() {
        int ordenarPor = jcbOrdenar.getSelectedIndex();
        //los valores q toma son el del atributo de Repuesto.class
        switch (ordenarPor) {
            case 0:
                return "id";
            case 1:
                return "montoTotal";
            default:
                return "id";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButTodasVentas = new javax.swing.JButton();
        jButVolver = new javax.swing.JButton();
        jButVerHoy = new javax.swing.JButton();
        jButVerDetalles = new javax.swing.JButton();
        jButImprimirFactura = new javax.swing.JButton();
        jButCancelarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButBuscar = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfMontoMinimo = new javax.swing.JTextField();
        jtfMontoMaximo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbOrdenar = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jcbTipoOrden = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jButTodasVentas.setText("TODAS LAS VENTAS");
        jButTodasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButTodasVentasActionPerformed(evt);
            }
        });

        jButVolver.setText("VOLVER");
        jButVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVolverActionPerformed(evt);
            }
        });

        jButVerHoy.setText("BUSCAR LAS DE HOY");
        jButVerHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerHoyActionPerformed(evt);
            }
        });

        jButVerDetalles.setText("VER DETALLES");
        jButVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButVerDetallesActionPerformed(evt);
            }
        });

        jButImprimirFactura.setText("IMPRIMIR FACTURA");
        jButImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButImprimirFacturaActionPerformed(evt);
            }
        });

        jButCancelarVenta.setText("CANCELAR VENTA");
        jButCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButImprimirFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButVerDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButVerHoy, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jButTodasVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButCancelarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButTodasVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVerHoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButVerDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButImprimirFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButCancelarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButVolver)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButBuscar.setText("BUSCAR");
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BUSCAR POR MONTO");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mínimo");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Máximo");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cualquiera", "Pendiente", "Pagada", "Cancelada" }));

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Para buscar por código (dejar vacío para cualquiera)");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado de ventas:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("---------");

        jLabel6.setText("*Proximamente buscar por fecha");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ordenar por:");

        jcbOrdenar.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jcbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Monto" }));

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de orden:");

        jcbTipoOrden.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jcbTipoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbOrdenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbTipoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMontoMinimo)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfMontoMaximo)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMontoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMontoMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButBuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbOrdenar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbTipoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVentas.setShowGrid(true);
        jScrollPane1.setViewportView(jTableVentas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVolverActionPerformed
        home.mostrarPanel("panelOpciones");
    }//GEN-LAST:event_jButVolverActionPerformed

    private void jButTodasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButTodasVentasActionPerformed
        tabla.setRowCount(0);
        listaParaTabla = ventaServ.todasVentas();
        llenaTabla(listaParaTabla);
    }//GEN-LAST:event_jButTodasVentasActionPerformed

    private void jButVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerDetallesActionPerformed
        VentaRepuesto ventaParaDetalle = new VentaRepuesto();
        int filaParaConsultar = jTableVentas.getSelectedRow();
        if (filaParaConsultar == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una venta.", "DEBE SELECCIONAR UNA VENTA",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Long codVentaElegido = Long.valueOf(jTableVentas.getValueAt(filaParaConsultar, 0).toString());
        //TO-DO: MOJORAR ESTO
        for (int i = 0; i < listaParaTabla.size(); i++) {
            if (Objects.equals(listaParaTabla.get(i).getId(), codVentaElegido)) {
                ventaParaDetalle = listaParaTabla.get(i);
            }
        }
        JDialogVentaDetalles jdvd = new JDialogVentaDetalles(null, false, ventaParaDetalle);
        jdvd.setVisible(true);

    }//GEN-LAST:event_jButVerDetallesActionPerformed

    private void jButVerHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButVerHoyActionPerformed
//        tabla.setRowCount(0);

    }//GEN-LAST:event_jButVerHoyActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
//        jLabMostrando.setText("Mostrando: ");
        EstadoVentaRepuesto estadoParaBuscar;
        Long codVentaIngresado = null;
        if (!jtfBuscar.getText().trim().isBlank() || !jtfBuscar.getText().trim().isEmpty()) {
            String cod = jtfBuscar.getText().trim();
            try {
                verificadorCampos.verificaFormatoLong(cod, "de búsqueda");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "HAY CAMPOS EN MAL FORMATO",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            codVentaIngresado = Long.valueOf(cod);
//            jLabMostrando.setText(jLabMostrando.getText().concat("& Código de venta: " + cod + " "));
        }
        BigDecimal montoMinimo = null;
        BigDecimal montoMaximo = null;
        if (!jtfMontoMinimo.getText().trim().isBlank() && !jtfMontoMinimo.getText().trim().isEmpty()) {
            montoMinimo = BigDecimal.valueOf(Double.parseDouble(jtfMontoMinimo.getText().trim())).setScale(2, RoundingMode.HALF_UP);
//            jLabMostrando.setText(jLabMostrando.getText().concat("& Monto Mínimo: " + montoMinimo + " "));
        }
        if (!jtfMontoMaximo.getText().trim().isBlank() && !jtfMontoMaximo.getText().trim().isEmpty()) {
            montoMaximo = BigDecimal.valueOf(Double.parseDouble(jtfMontoMaximo.getText().trim())).setScale(2, RoundingMode.HALF_UP);
//            jLabMostrando.setText(jLabMostrando.getText().concat("& Monto Máximo: " + montoMaximo + " "));
        }
        int seleccionEstadoVenta = jcbEstado.getSelectedIndex();
        switch (seleccionEstadoVenta) {
            case 0: //se eligió: cualquiera
                estadoParaBuscar = null;
                break;
            case 1: //se eligió: pendiente
                estadoParaBuscar = EstadoVentaRepuesto.PENDIENTE_PAGO;
//                jLabMostrando.setText(jLabMostrando.getText().concat("& Estado: aceptadas "));
                break;
            case 2: //se eligió: pagado
                estadoParaBuscar = EstadoVentaRepuesto.PAGADO;
//                jLabMostrando.setText(jLabMostrando.getText().concat("& Estado: pagadas "));
                break;
            case 3: //se eligió: cancelado
                estadoParaBuscar = EstadoVentaRepuesto.CANCELADO;
//                jLabMostrando.setText(jLabMostrando.getText().concat("& Estado: canceladas "));
                break;
            default:
                System.out.println("////////////////////" + seleccionEstadoVenta);
                return;
        }
        String columnaParaOrdenamiento = tomaOrdenEligido();
        Integer tipoOrdenElegido = jcbTipoOrden.getSelectedIndex();
        listaParaTabla = ventaServ.buscarVentas(codVentaIngresado, estadoParaBuscar, montoMinimo,
                montoMaximo, columnaParaOrdenamiento, tipoOrdenElegido);
        tabla.setRowCount(0);
        llenaTabla(listaParaTabla);

    }//GEN-LAST:event_jButBuscarActionPerformed

    private void jButCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelarVentaActionPerformed
        VentaRepuesto ventaParaCancelar = new VentaRepuesto();
        int filaParaCancelar = jTableVentas.getSelectedRow();
        if (filaParaCancelar == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una venta.", "DEBE SELECCIONAR UNA VENTA",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Long codVentaElegido = Long.valueOf(jTableVentas.getValueAt(filaParaCancelar, 0).toString());
        //TO-DO: MOJORAR ESTO
        for (int i = 0; i < listaParaTabla.size(); i++) {
            if (Objects.equals(listaParaTabla.get(i).getId(), codVentaElegido)) {
                ventaParaCancelar = listaParaTabla.get(i);
            }
        }
        ventaParaCancelar.setEstadoVenta(EstadoVentaRepuesto.CANCELADO);
        int respuesta = JOptionPane.showConfirmDialog(null,
                "Esta a punto de cancelar una venta, esta acción es irreversible. ¿Continuar?",
                "CONFIRMACIÓN DE CANCELADO", JOptionPane.WARNING_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            int respuesta2 = JOptionPane.showConfirmDialog(null,
                    "Confirmar eliminación de venta nro: " + ventaParaCancelar.getId(),
                    "CONFIRMACIÓN DE BORRADO", JOptionPane.WARNING_MESSAGE);
            if (respuesta2 == JOptionPane.YES_OPTION) {
                //TO-DO: GESTIONAR ERRORES
                ventaServ.modificarVenta(ventaParaCancelar);
                JOptionPane.showMessageDialog(null, "Venta cancelada correctamente.",
                        "CANCELACIÓN DE VENTA", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButCancelarVentaActionPerformed

    private void jButImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButImprimirFacturaActionPerformed
        VentaRepuesto ventaParaImprimir = new VentaRepuesto();
        int filaParaImprimir = jTableVentas.getSelectedRow();
        if (filaParaImprimir == -1) {
            JOptionPane.showMessageDialog(null, "No ha seleccionado una venta.", "DEBE SELECCIONAR UNA VENTA",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Long codVentaElegido = Long.valueOf(jTableVentas.getValueAt(filaParaImprimir, 0).toString());
        //TO-DO: MOJORAR ESTO
        for (int i = 0; i < listaParaTabla.size(); i++) {
            if (Objects.equals(listaParaTabla.get(i).getId(), codVentaElegido)) {
                ventaParaImprimir = listaParaTabla.get(i);
            }
        }

        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            if (!ruta.endsWith(".pdf")) {
                ruta += ".pdf";
            }
            GeneradorPDF.generaPDFVenta(ventaParaImprimir, ruta);
        }
    }//GEN-LAST:event_jButImprimirFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButCancelarVenta;
    private javax.swing.JButton jButImprimirFactura;
    private javax.swing.JButton jButTodasVentas;
    private javax.swing.JButton jButVerDetalles;
    private javax.swing.JButton jButVerHoy;
    private javax.swing.JButton jButVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbOrdenar;
    private javax.swing.JComboBox<String> jcbTipoOrden;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfMontoMaximo;
    private javax.swing.JTextField jtfMontoMinimo;
    // End of variables declaration//GEN-END:variables
}
