package GUI.panels;

import GUI.Inicio;
import GUI.JFrameHome;
import entities.Usuario;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import services.UsuarioServ;
import util.VerificadorCampos;

public class PanelInicioSesion extends javax.swing.JPanel {

    private Inicio inicio;

    private UsuarioServ usuarioServ = new UsuarioServ();

    private VerificadorCampos verificadorCampos = new VerificadorCampos();

    public PanelInicioSesion() {
        initComponents();
    }

    public PanelInicioSesion(Inicio inicio) {
        initComponents();
        this.inicio = inicio;

//        ImageIcon iconoSinEscalar = new ImageIcon(getClass().getResource("/imgs/logo150x100.png"));
//        Image imagen = iconoSinEscalar.getImage().getScaledInstance(150, 100, Image.SCALE_SMOOTH);
//        ImageIcon iconoEscalado = new ImageIcon(imagen);
//        jLabel4.setIcon(iconoEscalado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButAcceder = new javax.swing.JButton();
        jLabNombreUsuario = new javax.swing.JLabel();
        jlabContrasenia = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jpfPassword = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesión");

        jButton1.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton1.setText("Crear nuevo usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButAcceder.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButAcceder.setText("Acceder");
        jButAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAccederActionPerformed(evt);
            }
        });

        jLabNombreUsuario.setText("Nombre de usuario");

        jlabContrasenia.setText("Contraseña");

        jLabel4.setBackground(new java.awt.Color(102, 0, 255));
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo150x100.png"))); // NOI18N

        jButton3.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        jButton3.setText("Recuperar contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButAcceder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabContrasenia)
                            .addComponent(jLabNombreUsuario))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButAcceder)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicio.mostrarPanel("panelNuevoUsuario");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAccederActionPerformed
        try {
            verificadorCampos.verificarVacio(jtfNombreUsuario.getText().trim(), jLabNombreUsuario.getText());
            //TO-DO: HACER ESTO BIEN POR EL AMOR DE DIOS
            verificadorCampos.verificarVacio(jpfPassword.getPassword().toString(), jlabContrasenia.getText());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return;
        }
        Usuario usuario = usuarioServ.buscarUsuario(1L);
        
        inicio.dispose();

        JFrameHome jFrameHome = new JFrameHome(usuario);
//        jFrameHome.setMinimumSize(new Dimension(900, 590));
        jFrameHome.setVisible(true);
    }//GEN-LAST:event_jButAccederActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAcceder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabContrasenia;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
