package GUI.panels;

import GUI.Inicio;
import entities.Usuario;
import enums.PrivilegioUsuario;
import java.util.Arrays;
import javax.swing.JOptionPane;
import services.UsuarioServ;
import util.VerificadorCampos;

public class PanelNuevoUsuario extends javax.swing.JPanel {

    private Inicio inicio;

    private VerificadorCampos verificadorCampos = new VerificadorCampos();

    private UsuarioServ usuarioServ = new UsuarioServ();

    public PanelNuevoUsuario() {
        initComponents();
    }

    public PanelNuevoUsuario(Inicio inicio) {
        initComponents();
        this.inicio = inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrearUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbRoles = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jtfConfirmPassword = new javax.swing.JPasswordField();

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo usuario");

        btnCrearUsuario.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        btnCrearUsuario.setText("Crear usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de usuario");

        jLabel3.setText("Rol de usuario");

        jcbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un rol...", "Gerente", "Jefe Taller", "Jefe Ventas", "Jefe Recepción", "Jefe Depósito", "Operario Taller", "Operario Ventas", "Operario Recepción", "Operario Depósito" }));

        jLabel4.setText("Contraseña");

        jLabel5.setText("Confirme contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfNombre)
                    .addComponent(jcbRoles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtfPassword)
                    .addComponent(jtfConfirmPassword))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnCrearUsuario)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(btnCrearUsuario)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        String nombre = jtfNombre.getText().trim();
        int rollegido = jcbRoles.getSelectedIndex();
        char[] pass = jtfPassword.getPassword();
//        char[] passconfirm = jtfConfirmPassword.getPassword();
        try {
            verificadorCampos.verificarVacio(nombre, jLabel2.getText());
            verificadorCampos.verificaLargo(nombre, 25, jLabel2.getText());
            verificadorCampos.verificaPassword(pass);
//            verificadorCampos.verificaPassword(passconfirm);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(inicio, e.getMessage(), "ERROR AL CREAR USUARIO",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
//        if (pass.toString() != passconfirm.toString()) {
//            JOptionPane.showMessageDialog(inicio, "La confirmación de contraseña no coincide",
//                    "ERROR AL CONFIRMAR CONTRASEÑA", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        if (rollegido == 0) {
            JOptionPane.showMessageDialog(inicio, "Debe elegir un rol para el usuario.",
                    "ERROR AL CREAR USUARIO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //TO-DO: implementar seguridad en la contraseña
        //MUY MALA PRÁCTICA PONER CONTRASEÑA EN STRING
        Usuario usuario = new Usuario(null, nombre, Arrays.toString(pass),
                PrivilegioUsuario.devuelvePrivPorNumero(rollegido));

        usuarioServ.cargarUsuario(usuario);

        Arrays.fill(pass, '\0');
//        Arrays.fill(passconfirm, '\0');
        JOptionPane.showMessageDialog(inicio, "Usuario creado correctamente.",
                "CREACIÓN DE USUARIO", JOptionPane.INFORMATION_MESSAGE);
        inicio.mostrarPanel("panelInicioSesion");
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> jcbRoles;
    private javax.swing.JPasswordField jtfConfirmPassword;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JPasswordField jtfPassword;
    // End of variables declaration//GEN-END:variables
}
